language: ruby
cache: bundler
rvm:
  - 2.1
  - 2.2
gemfile:
  - gemfiles/puppet3.gemfile
  - gemfiles/puppet4.gemfile
script:
  - "bundle exec rake validate"
  - "bundle exec rake lint"
  - "bundle exec rake spec"
